export const newUser = [
  {
    name: "first_name",
    size: "small",
    label: "Firstname",
    required: true,
    xs: 6,
  },
  {
    name: "last_name",
    size: "small",
    label: "Lastname",
    required: true,
    xs: 6,
  },
  {
    name: "age",
    size: "small",
    label: "Age",
    required: false,
    xs: 6,
  },
  {
    name: "phone_number",
    size: "small",
    label: "Phone number",
    required: false,
    xs: 6,
  },
  {
    name: "username",
    size: "small",
    required: true,
    label: "Username",
    xs: 12,
  },
  {
    name: "email",
    size: "small",
    required: true,
    label: "Email",
    xs: 12,
  },
  {
    name: "user_password",
    size: "small",
    required: true,
    label: "Password",
    type: "password",
    autoComplete: "new-password",
    xs: 6,
  },
  {
    name: "user_verification_password",
    size: "small",
    required: true,
    label: "Verify Password",
    type: "password",
    autoComplete: "new-password",
    xs: 6,
  },
];
